services:
  nginx:
    image: nginx:stable-alpine
    # command: [nginx-debug, "-g", "daemon off;"]
    volumes:
      - ./public_html:/app:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.error.log:/var/logs/nginx/site.error.log
    ports:
      - ${PORT:-1902}:80

  mysql:
    image: mariadb:11.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
    volumes:
      - db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      # for backup restoration
      # - ./docker/halicrime.sql:/docker-entrypoint-initdb.d/db_dump.sql
    restart: on-failure:3

  php:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    env_file: .env
    volumes:
      - ./:/app
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
    restart: on-failure:3

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: ${MYSQL_USER:-dbuser}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD:-dbpass}

volumes:
  db:
